/* eslint-disable */
const normal = {
  'type': 'normal',
  'total': 24,
  'rows': 4,
  'cols': 6,
  'items': [{
    'id': null,
    'state': 'normal',
    'type': 'row_title',
    'tags': [],
    'graph': {'x': 75, 'y': 150, 'width': 50, 'height': 50},
    'title': 'A',
  }, {
    'id': null,
    'state': 'normal',
    'type': 'col_title',
    'tags': [],
    'graph': {'x': 150, 'y': 75, 'width': 50, 'height': 50},
    'title': '1',
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [2],
    'graph': {'x': 150, 'y': 150, 'width': 50, 'height': 50},
    'title': '1A',
  }, {
    'id': null,
    'state': 'normal',
    'type': 'col_title',
    'tags': [],
    'graph': {'x': 315, 'y': 75, 'width': 50, 'height': 50},
    'title': '2',
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [1, 2],
    'graph': {'x': 315, 'y': 150, 'width': 50, 'height': 50},
    'title': '2A',
  }, {
    'id': null,
    'state': 'normal',
    'type': 'col_title',
    'tags': [],
    'graph': {'x': 390, 'y': 75, 'width': 50, 'height': 50},
    'title': '3',
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [1, 2, 3],
    'graph': {'x': 390, 'y': 150, 'width': 50, 'height': 50},
    'title': '3A',
  }, {
    'id': null,
    'state': 'normal',
    'type': 'col_title',
    'tags': [],
    'graph': {'x': 465, 'y': 75, 'width': 50, 'height': 50},
    'title': '4',
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [1, 3],
    'graph': {'x': 465, 'y': 150, 'width': 50, 'height': 50},
    'title': '4A',
  }, {
    'id': null,
    'state': 'normal',
    'type': 'col_title',
    'tags': [],
    'graph': {'x': 640, 'y': 75, 'width': 50, 'height': 50},
    'title': '5',
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [3],
    'graph': {'x': 640, 'y': 150, 'width': 50, 'height': 50},
    'title': '5A',
  }, {
    'id': null,
    'state': 'normal',
    'type': 'col_title',
    'tags': [],
    'graph': {'x': 715, 'y': 75, 'width': 50, 'height': 50},
    'title': '6',
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [3],
    'graph': {'x': 715, 'y': 150, 'width': 50, 'height': 50},
    'title': '6A',
  }, {
    'id': null,
    'state': 'normal',
    'type': 'row_title',
    'tags': [],
    'graph': {'x': 75, 'y': 225, 'width': 50, 'height': 50},
    'title': 'B',
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [2],
    'graph': {'x': 150, 'y': 225, 'width': 50, 'height': 50},
    'title': '1B',
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [1, 2],
    'graph': {'x': 315, 'y': 225, 'width': 50, 'height': 50},
    'title': '2B',
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [1, 2, 3],
    'graph': {'x': 390, 'y': 225, 'width': 50, 'height': 50},
    'title': '3B',
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [1, 3],
    'graph': {'x': 465, 'y': 225, 'width': 50, 'height': 50},
    'title': '4B',
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [3],
    'graph': {'x': 640, 'y': 225, 'width': 50, 'height': 50},
    'title': '5B',
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [3],
    'graph': {'x': 715, 'y': 225, 'width': 50, 'height': 50},
    'title': '6B',
  }, {
    'id': null,
    'state': 'normal',
    'type': 'row_title',
    'tags': [],
    'graph': {'x': 75, 'y': 300, 'width': 50, 'height': 50},
    'title': 'C',
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [2],
    'graph': {'x': 150, 'y': 300, 'width': 50, 'height': 50},
    'title': '1C',
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [1, 2],
    'graph': {'x': 315, 'y': 300, 'width': 50, 'height': 50},
    'title': '2C',
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [1, 2, 3],
    'graph': {'x': 390, 'y': 300, 'width': 50, 'height': 50},
    'title': '3C',
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [1, 3],
    'graph': {'x': 465, 'y': 300, 'width': 50, 'height': 50},
    'title': '4C',
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [3],
    'graph': {'x': 640, 'y': 300, 'width': 50, 'height': 50},
    'title': '5C',
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [3],
    'graph': {'x': 715, 'y': 300, 'width': 50, 'height': 50},
    'title': '6C',
  }, {
    'id': null,
    'state': 'normal',
    'type': 'row_title',
    'tags': [],
    'graph': {'x': 75, 'y': 375, 'width': 50, 'height': 50},
    'title': 'D',
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [2],
    'graph': {'x': 150, 'y': 375, 'width': 50, 'height': 50},
    'title': '1D',
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [1, 2],
    'graph': {'x': 315, 'y': 375, 'width': 50, 'height': 50},
    'title': '2D',
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [1, 2, 3],
    'graph': {'x': 390, 'y': 375, 'width': 50, 'height': 50},
    'title': '3D',
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [1, 3],
    'graph': {'x': 465, 'y': 375, 'width': 50, 'height': 50},
    'title': '4D',
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [3],
    'graph': {'x': 640, 'y': 375, 'width': 50, 'height': 50},
    'title': '5D',
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [3],
    'graph': {'x': 715, 'y': 375, 'width': 50, 'height': 50},
    'title': '6D',
  }],
  'background': {'url': null, 'width': null, 'height': null},
}

const custom = {
  'type': 'custom',
  'total': 0,
  'rows': 4,
  'cols': 6,
  'items': [{'type': 'background', 'graph': {'x': 0, 'y': 0, 'width': 800, 'height': 600}}, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [],
    'graph': {'x': 210, 'y': 150, 'width': 50, 'height': 50},
    'title': null,
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [1, 2, 3],
    'graph': {'x': 410, 'y': 40, 'width': 50, 'height': 50},
    'title': null,
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [2],
    'graph': {'x': 740, 'y': 270, 'width': 50, 'height': 50},
    'title': null,
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [3],
    'graph': {'x': 410, 'y': 334, 'width': 50, 'height': 50},
    'title': null,
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [],
    'graph': {'x': 175, 'y': 384, 'width': 50, 'height': 50},
    'title': null,
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [],
    'graph': {'x': 430, 'y': 210, 'width': 50, 'height': 50},
    'title': null,
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [],
    'graph': {'x': 640, 'y': 250, 'width': 50, 'height': 50},
    'title': null,
  }],
  'background': {'url': '/bg.jpg', 'width': null, 'height': null},
}

export default {
  normal, custom,
}
