/* eslint-disable */
const normal = {
  'type': 'normal',
  'total': 0,
  'rows': 4,
  'cols': 6,
  'items': [{
    'id': 1,
    'state': 'normal',
    'type': 'row_title',
    'tags': [],
    'graph': {'x': 75, 'y': 150, 'width': 50, 'height': 50},
    'title': 'A',
  }, {
    'id': 2,
    'state': 'normal',
    'type': 'col_title',
    'tags': [],
    'graph': {'x': 150, 'y': 75, 'width': 50, 'height': 50},
    'title': '1',
  }, {
    'id': 3,
    'state': 'normal',
    'type': 'seat',
    'booking_state': 'bookable',
    'tags': [2],
    'graph': {'x': 150, 'y': 150, 'width': 50, 'height': 50},
    'title': '1A',
  }, {
    'id': 4,
    'state': 'normal',
    'type': 'col_title',
    'tags': [],
    'graph': {'x': 255, 'y': 75, 'width': 50, 'height': 50},
    'title': '2',
  }, {
    'id': 5,
    'state': 'normal',
    'type': 'seat',
    'booking_state': 'bookable',
    'tags': [1, 2],
    'graph': {'x': 255, 'y': 150, 'width': 50, 'height': 50},
    'title': '2A',
  }, {
    'id': 6,
    'state': 'normal',
    'type': 'col_title',
    'tags': [],
    'graph': {'x': 330, 'y': 75, 'width': 50, 'height': 50},
    'title': '3',
  }, {
    'id': 7,
    'state': 'normal',
    'type': 'seat',
    'booking_state': 'booked_period',
    'tags': [1, 2, 3],
    'graph': {'x': 330, 'y': 150, 'width': 50, 'height': 50},
    'title': '3A',
  }, {
    'id': 8,
    'state': 'normal',
    'type': 'col_title',
    'tags': [],
    'graph': {'x': 405, 'y': 75, 'width': 50, 'height': 50},
    'title': '4',
  }, {
    'id': 9,
    'state': 'normal',
    'type': 'seat',
    'booking_state': 'bookable',
    'tags': [1, 3],
    'graph': {'x': 405, 'y': 150, 'width': 50, 'height': 50},
    'title': '4A',
  }, {
    'id': 10,
    'state': 'normal',
    'type': 'col_title',
    'tags': [],
    'graph': {'x': 500, 'y': 75, 'width': 50, 'height': 50},
    'title': '5',
  }, {
    'id': 11,
    'state': 'normal',
    'type': 'seat',
    'booking_state': 'booked_period',
    'tags': [3],
    'graph': {'x': 500, 'y': 150, 'width': 50, 'height': 50},
    'title': '5A',
  }, {
    'id': 12,
    'state': 'normal',
    'type': 'col_title',
    'tags': [],
    'graph': {'x': 575, 'y': 75, 'width': 50, 'height': 50},
    'title': '6',
  }, {
    'id': 13,
    'state': 'normal',
    'type': 'seat',
    'booking_state': 'bookable',
    'tags': [3],
    'graph': {'x': 575, 'y': 150, 'width': 50, 'height': 50},
    'title': '6A',
  }, {
    'id': 14,
    'state': 'normal',
    'type': 'row_title',
    'tags': [],
    'graph': {'x': 75, 'y': 225, 'width': 50, 'height': 50},
    'title': 'B',
  }, {
    'id': 15,
    'state': 'not_show',
    'type': 'seat',
    'booking_state': 'booked_period',
    'tags': [2],
    'graph': {'x': 150, 'y': 225, 'width': 50, 'height': 50},
    'title': '1B',
  }, {
    'id': 16,
    'state': 'normal',
    'type': 'seat',
    'booking_state': 'bookable',
    'tags': [1, 2],
    'graph': {'x': 255, 'y': 225, 'width': 50, 'height': 50},
    'title': '2B',
  }, {
    'id': 17,
    'state': 'normal',
    'type': 'seat',
    'booking_state': 'bookable',
    'tags': [1, 2, 3],
    'graph': {'x': 330, 'y': 225, 'width': 50, 'height': 50},
    'title': '3B',
  }, {
    'id': 18,
    'state': 'normal',
    'type': 'seat',
    'booking_state': 'booked',
    'tags': [1, 3],
    'graph': {'x': 405, 'y': 225, 'width': 50, 'height': 50},
    'title': '4B',
  }, {
    'id': 19,
    'state': 'normal',
    'type': 'seat',
    'booking_state': 'bookable',
    'tags': [3],
    'graph': {'x': 500, 'y': 225, 'width': 50, 'height': 50},
    'title': '5B',
  }, {
    'id': 20,
    'state': 'normal',
    'type': 'seat',
    'booking_state': 'booked',
    'tags': [3],
    'graph': {'x': 575, 'y': 225, 'width': 50, 'height': 50},
    'title': '6B',
  }, {
    'id': 21,
    'state': 'normal',
    'type': 'row_title',
    'tags': [],
    'graph': {'x': 75, 'y': 300, 'width': 50, 'height': 50},
    'title': 'C',
  }, {
    'id': 22,
    'state': 'blocked',
    'type': 'seat',
    'booking_state': 'bookable',
    'tags': [2],
    'graph': {'x': 150, 'y': 300, 'width': 50, 'height': 50},
    'title': '1C',
  }, {
    'id': 23,
    'state': 'normal',
    'type': 'seat',
    'booking_state': 'booked',
    'tags': [1, 2],
    'graph': {'x': 255, 'y': 300, 'width': 50, 'height': 50},
    'title': '2C',
  }, {
    'id': 24,
    'state': 'normal',
    'type': 'seat',
    'booking_state': 'pending',
    'tags': [1, 2, 3],
    'graph': {'x': 330, 'y': 300, 'width': 50, 'height': 50},
    'title': '3C',
  }, {
    'id': 25,
    'state': 'normal',
    'type': 'seat',
    'booking_state': 'pending',
    'tags': [1, 3],
    'graph': {'x': 405, 'y': 300, 'width': 50, 'height': 50},
    'title': '4C',
  }, {
    'id': 26,
    'state': 'normal',
    'type': 'seat',
    'booking_state': 'bookable',
    'tags': [3],
    'graph': {'x': 500, 'y': 300, 'width': 50, 'height': 50},
    'title': '5C',
  }, {
    'id': 27,
    'state': 'normal',
    'type': 'seat',
    'booking_state': 'bookable',
    'tags': [3],
    'graph': {'x': 575, 'y': 300, 'width': 50, 'height': 50},
    'title': '6C',
  }, {
    'id': 28,
    'state': 'normal',
    'type': 'row_title',
    'tags': [],
    'graph': {'x': 75, 'y': 375, 'width': 50, 'height': 50},
    'title': 'D',
  }, {
    'id': 29,
    'state': 'normal',
    'type': 'seat',
    'booking_state': 'pending',
    'tags': [2],
    'graph': {'x': 150, 'y': 375, 'width': 50, 'height': 50},
    'title': '1D',
  }, {
    'id': 30,
    'state': 'normal',
    'type': 'seat',
    'booking_state': 'bookable',
    'tags': [1, 2],
    'graph': {'x': 255, 'y': 375, 'width': 50, 'height': 50},
    'title': '2D',
  }, {
    'id': 31,
    'state': 'normal',
    'type': 'seat',
    'booking_state': 'bookable',
    'tags': [1, 2, 3],
    'graph': {'x': 330, 'y': 375, 'width': 50, 'height': 50},
    'title': '3D',
  }, {
    'id': 32,
    'state': 'normal',
    'type': 'seat',
    'booking_state': 'pending',
    'tags': [1, 3],
    'graph': {'x': 405, 'y': 375, 'width': 50, 'height': 50},
    'title': '4D',
  }, {
    'id': 33,
    'state': 'normal',
    'type': 'seat',
    'booking_state': 'bookable',
    'tags': [3],
    'graph': {'x': 500, 'y': 375, 'width': 50, 'height': 50},
    'title': '5D',
  }, {
    'id': 34,
    'state': 'normal',
    'type': 'seat',
    'booking_state': 'bookable',
    'tags': [3],
    'graph': {'x': 575, 'y': 375, 'width': 50, 'height': 50},
    'title': '6D',
  }],
  'background': {'url': '/bg.jpg', 'width': null, 'height': null},
}

const custom = {
  'type': 'custom',
  'total': 0,
  'rows': 4,
  'cols': 6,
  'items': [{'type': 'background', 'graph': {'x': 0, 'y': 0, 'width': 800, 'height': 600}}, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [],
    'graph': {'x': 210, 'y': 150, 'width': 50, 'height': 50},
    'title': null,
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [1, 2, 3],
    'graph': {'x': 410, 'y': 40, 'width': 50, 'height': 50},
    'title': null,
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [2],
    'graph': {'x': 740, 'y': 270, 'width': 50, 'height': 50},
    'title': null,
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [3],
    'graph': {'x': 410, 'y': 334, 'width': 50, 'height': 50},
    'title': null,
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [],
    'graph': {'x': 175, 'y': 384, 'width': 50, 'height': 50},
    'title': null,
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [],
    'graph': {'x': 430, 'y': 210, 'width': 50, 'height': 50},
    'title': null,
  }, {
    'id': null,
    'state': 'normal',
    'type': 'seat',
    'tags': [],
    'graph': {'x': 640, 'y': 250, 'width': 50, 'height': 50},
    'title': null,
  }],
  'background': {'url': '/bg.jpg', 'width': null, 'height': null},
}

export default {
  normal, custom,
}
